apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: dhub.c2.croc.ru/kaas/aws-ebs-csi-driver
    newTag: v1.1.1
  - name: dhub.c2.croc.ru/kaas/csi-provisioner
    newTag: v2.1.1
  - name: dhub.c2.croc.ru/kaas/csi-attacher
    newTag: v3.1.0
  - name: dhub.c2.croc.ru/kaas/livenessprobe
    newTag: v2.2.0
  - name: dhub.c2.croc.ru/kaas/csi-node-driver-registrar
    newTag: v2.1.0
